alias fc='nvim ~/.config/fish/config.fish'
alias lc='nvim ~/.config/fish/conf.d/laravel.fish'
alias vc='nvim ~/.config/fish/conf.d/flutter.fish'
alias jc='nvim ~/.config/fish/conf.d/java.fish'
alias workspace='open ~/Projects'
#alias activate='source venv/bin/activate.fish'
